spring.application.name=lets-play
server.port=8080

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=lets-play
spring.data.mongodb.username=bloguser
spring.data.mongodb.password=blogpass
spring.data.mongodb.authentication-database=admin
